// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson10b21d34DecodeGithubComMachinefiW3bstreamWasmGolangSdkExamplesEasyjsonModel(in *jlexer.Lexer, out *School) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "school_name":
			out.Name = string(in.String())
		case "school_addr":
			out.Addr = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson10b21d34EncodeGithubComMachinefiW3bstreamWasmGolangSdkExamplesEasyjsonModel(out *jwriter.Writer, in School) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"school_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"school_addr\":"
		out.RawString(prefix)
		out.String(string(in.Addr))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v School) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson10b21d34EncodeGithubComMachinefiW3bstreamWasmGolangSdkExamplesEasyjsonModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v School) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson10b21d34EncodeGithubComMachinefiW3bstreamWasmGolangSdkExamplesEasyjsonModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *School) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson10b21d34DecodeGithubComMachinefiW3bstreamWasmGolangSdkExamplesEasyjsonModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *School) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson10b21d34DecodeGithubComMachinefiW3bstreamWasmGolangSdkExamplesEasyjsonModel(l, v)
}
